#region license

//Copyright 2009 Zack Owens

//Licensed under the Microsoft Public License (Ms-PL) (the "License"); 
//you may not use this file except in compliance with the License. 
//You may obtain a copy of the License at 

//http://clubstarterkit.codeplex.com/license

//Unless required by applicable law or agreed to in writing, software 
//distributed under the License is distributed on an "AS IS" BASIS, 
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
//See the License for the specific language governing permissions and 
//limitations under the License. 

#endregion

using System.Web.Security;

namespace ClubStarterKit.Infrastructure
{
    public interface IPasswordCryptographyProvider
    {
        /// <summary>
        /// Membership provider-specific password format
        /// </summary>
        MembershipPasswordFormat Format { get; }

        /// <summary>
        /// Generates a random salt
        /// </summary>
        /// <returns></returns>
        string GenerateSalt();

        /// <summary>
        /// Generates a password for the user
        /// </summary>
        /// <param name="plainTest">Plain text password (user input)</param>
        /// <param name="salt">Password salt generated by this provider</param>
        /// <returns>Salted password</returns>
        string GeneratePassword(string plainTest, string salt);

        /// <summary>
        /// Password is valid given salted password, salt and plain text
        /// </summary>
        /// <param name="saltedPassword">Salted password generated by this provider</param>
        /// <param name="salt">Salt generated by this provider</param>
        /// <param name="plainText">Plain Text password (user input)</param>
        /// <returns>True if the plain text password is the same as the salted password</returns>
        bool ValidatePassword(string saltedPassword, string salt, string plainText);
    }
}